-   id: poetry-generate-requirements
    name: Generate requirements.txt
    entry: poetry export
    args:
      [
        '-f',
        'requirements.txt',
        '-o',
        'requirements.txt',
        '--without-hashes',
      ]
    pass_filenames: false
    language: python
    files: 'poetry.lock'
    additional_dependencies: ["poetry"]